/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package tv.ouya.demo.OuyaUnityApplication;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int app_icon=0x7f020000;
        public static final int ouya_icon=0x7f020001;
    }
    public static final class id {
        public static final int mainLayout=0x7f060000;
        public static final int unityLayout=0x7f060001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class raw {
        public static final int key=0x7f040000;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
    }
}
