using System;
using UnityEngine;


namespace InControl
{
	public class UnityInputDeviceProfileList : ScriptableObject
	{
		public static string[] Profiles = new string[] 
		{
			"InControl.AmazonFireTVProfile",
			"InControl.AmazonFireTVRemote",
			"InControl.AndroidTVProfile",
			"InControl.AndroidTVRemoteProfile",
			"InControl.AppleMFiProfile",
			"InControl.ExecutionerXProfile",
			"InControl.GameStickLinuxProfile",
			"InControl.GameStickProfile",
			"InControl.GenericAndroidProfile",
			"InControl.GenericBlackBerryProfile",
			"InControl.GenericLinuxProfile",
			"InControl.GoogleNexusPlayerProfile",
			"InControl.GoogleNexusPlayerRemoteProfile",
			"InControl.GreenThrottleAtlasAndroidProfile",
			"InControl.HamaBlackForceWinProfile",
			"InControl.LogitechF310LinuxProfile",
			"InControl.LogitechF310ModeDMacProfile",
			"InControl.LogitechF310ModeDWinProfile",
			"InControl.LogitechF310ModeXMacProfile",
			"InControl.LogitechF310ModeXWinProfile",
			"InControl.LogitechF510LinuxProfile",
			"InControl.LogitechF510WinProfile",
			"InControl.LogitechF710LinuxProfile",
			"InControl.LogitechF710MacProfile",
			"InControl.LogitechF710ModeDWinProfile",
			"InControl.LogitechF710ModeXWinProfile",
			"InControl.LogitechRumblePad2MacProfile",
			"InControl.LogitechRumblePad2WinProfile",
			"InControl.LogitechWingManWinProfile",
			"InControl.MaxFireBlaze5Profile",
			"InControl.MogaProLinuxProfile",
			"InControl.MogaProMacProfile",
			"InControl.MogaProWinProfile",
			"InControl.NVidiaShieldAndroidProfile",
			"InControl.NVidiaShieldTabletProfile",
			"InControl.NatecGenesisP44Profile",
			"InControl.OuyaLinuxProfile",
			"InControl.OuyaWinProfile",
			"InControl.PlayStation2WinProfile",
			"InControl.PlayStation3AndroidProfile",
			"InControl.PlayStation3LinuxProfile",
			"InControl.PlayStation3MacProfile",
			"InControl.PlayStation3ShenghicWinProfile",
			"InControl.PlayStation3WinProfile",
			"InControl.PlayStation4AndroidProfile",
			"InControl.PlayStation4LinuxProfile",
			"InControl.PlayStation4MacBTProfile",
			"InControl.PlayStation4MacUSBProfile",
			"InControl.PlayStation4Profile",
			"InControl.PlayStation4WinProfile",
			"InControl.PlayStationVitaPSMProfile",
			"InControl.SamsungGP20AndroidProfile",
			"InControl.SpeedlinkStrikeMacProfile",
			"InControl.SpeedlinkStrikeWinProfile",
			"InControl.SteelSeriesFreeLinuxProfile",
			"InControl.SteelSeriesFreeMacProfile",
			"InControl.SteelSeriesFreeWinProfile",
			"InControl.ValveStreamingWinProfile",
			"InControl.Xbox360AndroidProfile",
			"InControl.Xbox360LinuxProfile",
			"InControl.Xbox360MacProfile",
			"InControl.Xbox360WinProfile",
			"InControl.XboxOneMacProfile",
			"InControl.XboxOneProfile",
			"InControl.XboxOneWinProfile",
		};
	}
}